# NumPy

#### 1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자.

In [ ]:
import numpy as np

arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


#### 모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자.

In [ ]:
arr1 = np.ones((3, 4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자.

In [ ]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 행렬
[[ 1, 2, 3, 4, 5], <br>
 [ 6, 7, 8, 9, 10], <br>
 [11, 12, 13, 14, 15], <br>
 [16, 17, 18, 19, 20], <br>
 [21, 22, 23, 24, 25]]

In [47]:
arr = np.arange(1, 26)
arr2d = arr.reshape(5, 5)

print(arr2d)
print()
print("shape:", arr2d.shape)

# 19
print(arr2d[arr2d == 19])
indices = np.where(arr2d == 19)
print(" 19 index:", indices[0][0], ",", indices[1][0], "\n")

# slicing
print(arr2d[3,3:], arr2d[4,3:])
print(arr2d[0:2])
print(arr2d[:,3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

shape: (5, 5)
[19]
 19 index: 3 , 3 

[19 20] [24 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


#### 행렬
[[[ 1  2  3  4], <br>
  [ 5  6  7  8], <br>
  [ 9 10 11 12]], <br><br>

 [[13 14 15 16], <br>
  [17 18 19 20], <br>
  [21 22 23 24]], <br><br>

 [[25 26 27 28], <br>
  [29 30 31 32], <br>
  [33 34 35 36]]]

In [65]:
arr = np.arange(1, 37)
arr3d = arr.reshape(3, 3, 4)

print(arr3d)
print("shape:", arr3d.shape)
print("size:", arr3d.size)

arr3d_reshaped = arr3d.reshape(3, 4, 3)
print("\n(3, 4, 3) array:")
print(arr3d_reshaped)
print("shape:", arr3d_reshaped.shape)
print("size:", arr3d_reshaped.size)

arr_flat = arr3d.flatten()
print("\nflat array:")
print(arr_flat)
print("shape:", arr_flat.shape)
print("size:", arr_flat.size)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
shape: (3, 3, 4)
size: 36

(3, 4, 3) array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
shape: (3, 4, 3)
size: 36

flat array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
shape: (36,)
size: 36


### 연산 연습
#### 국어, 영어 총점과 평균

In [64]:
kor = np.array([20, 30, 60])
eng = np.array([60, 40, 90])

print("국어 점수:", kor)
print("영어 점수:", eng)

tot_score = kor + eng
avg_score = tot_score / 2

print("개인 총점:", tot_score)
print("개인 평균:", avg_score)

print("국어 평균:", np.mean(kor))
print("영어 평균:", np.mean(eng))

국어 점수: [20 30 60]
영어 점수: [60 40 90]
개인 총점: [ 80  70 150]
개인 평균: [40. 35. 75.]
국어 평균: 36.666666666666664
영어 평균: 63.333333333333336
